### PR TITLE
markdown: add mathjax support

### LINKED ISSUE #12: LaTeX support?

### PR DESCRIPTION
**Pull request by matildepark**
Adds the [mathjax-react](https://github.com/CharlieMcVicker/mathjax-react) package and a Math component to display equations. In context, you'd use `{% math %}` to wrap an equation with an optional `block` parameter when you want it to be a block, not inline.

Fixes #12 

Open questions:

- This requires `String.raw()` to parse strings without assuming we're using backslashes as escapes, or else obviously LaTeX doesn't work. We can't really selectively do this processing, as the first time we pass a string without `String.raw()`, it seems to escape the slashes. Are there consequences of enforcing `String.raw()` on every single call of our Markdown parser? (How often are we using backslash escapes in our writing anyway?) Basically I want to test some Markdown processing more before merging.
- Obviously the above would be a big breaking change necessitating a major version bump. But does this even meet our needs? @sigilante If you can present some examples of what you'd want processed, it would help assess suitability.

Thus far `\sum_{2}^{\longrightarrow \beta}\equiv \beta\beta\beta\beta` becomes, well,

image

### CODE REVIEW

**Comment by sigilante** [comment]
Very exciting!

Looks like it's sticking with inline form rather than tall form.

We use `\` in some manual tree diagrams, for Bash line continuations, and in LaTeX.  Doesn't appear to be in anything else in `content/`.

Examples of what I am doing in LaTeX:

Hoon School, Mathematics:
image

```
$$
\sin(x) = \sum_{n=0}^\infty \frac{(-1)^n}{(2n+1)!}x^{2n+1}= x - \frac{x^3}{3!} + \frac{x^5}{5!} -   \frac{x^7}{7!} + \cdots
$$
```

Hoon School, Generic and Variant Cores:
image

```
$$
\int_a^b f(x) \, dx \approx \sum_{k=1}^N \frac{f(x_{k-1}) + f(x_k)}{2} \Delta x_k = \tfrac{\Delta x}{2  }\left(f(x_0) + 2f(x_1)+2f(x_2)+ 2f(x_3)+2f(x_4)+\cdots+2f(x_{N-1}) + f(x_N)\right)
$$
```

**Comment by matildepark** [comment]
> Looks like it's sticking with inline form rather than tall form.

Can you elaborate?

**Comment by sigilante** [comment]
The summation sigma should have the values above and below it (you can see this in my examples now) rather than at the side.  That's common for shorthand in running text but not ideal for standalone expressions.

**Comment by matildepark** [comment]
image

So it is ... let me see .....

**Comment by matildepark** [comment]
Adding `\displaystyle` seems to do it, but I don't know why it's assuming we're always inline. I need to look at MathJax config options.

image

**Comment by matildepark** [comment]
Oh wait. I'm dumb. I already had the answer with the `block` parameter!

image

`{% math block=true %}\sin(x) = \sum_{n=0}^\infty \frac{(-1)^n}{(2n+1)!}x^{2n+1}= x - \frac{x^3}{3!} + \frac{x^5}{5!} -   \frac{x^7}{7!} + \cdots{% /math %}`

**Comment by sigilante** [comment]
yes, that looks textbook!

**Comment by ghost** [comment]
> How often are we using backslash escapes in our writing anyway?

just went through all 893 instances of `\` in the developer docs:
- should be fine (these are the vast majority of backslashes, and are not used as escapes)
  - inline code
  - code blocks
  - the latex image urls
  - (though i guess you should check just to make sure: inline code (`` `\n` `` under `Et cetera.` heading of `jetting.md`), code block (`> =z ;p(class "\"><script src=\"example.com/xxx.js"): <h1>FOO</h1>` under `Sanitization` heading of `sail.md`))
- simple fix
  - the search key things (e.g. `\\\*\\@\\^\\?\\~`) in the irregular syntax page (`irregular.md`)
  - the 2 `\*`s under heading `` `++ship:enjs:format` `` in `2d_1-5.md` (can prob fix by using `&#42;` instead of `\*`)
  - the 2 `\>`s under heading `` `u3` Nouns `` in `jetting.md` (these backslashes don't actually do anything (is `>` regardless of whether md is `>` or `\>`) so should remove `\` to prevent it from showing up when using raw strings)
- could be an issue (i haven't tested tho so idk)
  - backslashes used to escape `|` chars in rows of markdown tables, so it doesn't detect the `|` as a row break. but if it does prevent you from having `|`s in rows you could just convert from regular markdown table to the `{% table %}`s
    - all the instances of this
      - the table just under the ``Additional `%roller` commmands`` heading in `roller-tutorial.md`
      - table at the top of `irregular.md`
  - the two `\\texttt`s under the heading `Declare function prototypes in headers.` in `jetting.md`

**Comment by matildepark** [comment]
I'm doing some integration testing with dev.urbit.org and hitting a weird quirk all the way up the stack — mathjax-react is a little temperamental. It won't render this one:

```
\int_a^b f(x) \, dx \approx \sum_{k=1}^N \frac{f(x_{k-1}) + f(x_k)}{2} \Delta x_k = \tfrac{\Delta x}{2  }\left(f(x_0) + 2f(x_1)+2f(x_2)+ 2f(x_3)+2f(x_4)+\cdots+2f(x_{N-1}) + f(x_N)\right)
```

Even if I go and pipe it in direct as so:

```js
return <MathComponent display={block} tex={String.raw`\int_a^b f(x) \, dx \approx \sum_{k=1}^N \frac{f(x_{k-1}) + f(x_k)}{2} \Delta x_k = \tfrac{\Delta x}{2  }\left(f(x_0) + 2f(x_1)+2f(x_2)+ 2f(x_3)+2f(x_4)+\cdots+2f(x_{N-1}) + f(x_N)\right)`} />;

```

But other MathJax renderers I can find can handle it — I can't see why it's specific to the package we're using here. The previous example, `\sin...` does work.

**Comment by matildepark** [comment]
Most other math does seem to work too going off MathJax documentation, though.

image

Matrices do not. They produce nothing. I am not sure why.

**Comment by matildepark** [comment]
The first example I said I had issues with, on inspection, say this:

image

@sigilante Honestly I don't know much about TeX so opinions welcome on what that whole thing means. Let me try matrices now.

**Comment by matildepark** [comment]
It's just a toss up what it'll take or not. It takes this just fine.

image

I'm presuming I have to do some MathJax configuration, but as I said, I know very little about math typesetting. I could ship this and see what we run into, since it otherwise works with little consequence on the docs. Opinion @sigilante?

**Comment by sigilante** [comment]
It probably has to do with which packages are being standardly included by MathJax.  I don't expect us to need anything odd, and it has `amsmath` out of the box.  `\tfrac` is pretty uncommon to need unless one is typesetting a textbook.

**Comment by sigilante** [comment]
Hmm, actually it may not be on by default:

> To enable any of the TeX extensions, simply add the appropriate string (e.g., "AMSmath.js") to the extensions array in the TeX block of your configuration. If you use one of the combined configuration files, like TeX-AMS_HTML, this will already include several of the extensions automatically, but you can include others using a mathjax configuration script prior to loading MathJax.

**Comment by matildepark** [comment]
> Hmm, actually it may not be on by default:
> 
> > To enable any of the TeX extensions, simply add the appropriate string (e.g., "AMSmath.js") to the extensions array in the TeX block of your configuration. If you use one of the combined configuration files, like TeX-AMS_HTML, this will already include several of the extensions automatically, but you can include others using a mathjax configuration script prior to loading MathJax.

Looks like it's covered in our package?

https://github.com/CharlieMcVicker/mathjax-react/blob/6e5c17d97a0da0ad518b0404cd2f1936990d4a92/src/utils/convert.ts#L23

**Comment by matildepark** [comment]
I'm in the middle of rewriting this so that we port [this gist](https://gist.github.com/GiacoCorsiglia/1619828473f4b34d3d914a16fcbf10f3) instead, because there isn't enough fine-grained configuration for me to add TeX extensions. Sampling the TeX we currently already have on the site we run into problems with, say, `{cases}` or what have you, and I'd like to at least add `\require` so you can ad hoc introduce TeX. This means making that gist work for Next.js and rewriting the component, then testing it again. I just would rather solve the problem than ship it with this many holes in it.

**Comment by matildepark** [comment]
So far so good.

```
{% math block=true %}
H(x)
=
\begin{cases} 1, & x > 0 \\\ 0, & x \le 0 \end{cases}
{% /math %}
```

Screen Shot 2022-10-05 at 3 08 57 PM
Screen Shot 2022-10-05 at 3 09 02 PM

(Previous image implementation vs. our native renderer.)

Note the third slash here. Not ideal, but apparently [line breaking is really hard and this is the workaround](https://github.com/mathjax/MathJax/issues/2312#issuecomment-581727345).  Let me prepare the commits.

**Comment by gmcz** [comment]
Looks great, @matildepark!

**Pull request merged**
